### ISSUE TITLE
improvements for the Seoul demo

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats#1]
# UI improvements for the Seoul demo

  - [x] "beta" text: please a bit smaller, slightly different color. 
  - [ ] <del>please add a "fork me on github" indicator. Example: https://www.bettercrypto.org/</del>
    - [x] Link in footer to source code (maybe add to about page too)
  - [x] please upload the source code for generating the UI/site to this repo
  - [x] score is still a "%" in the risks page. Needs to change
  - [ ]  <del>layout seems to be only semi-suitable for fluid like devices (iPads, iphone). Still having issues on very small displays (minor issue)</del>
  - [ ] <del>formula: can we render the formula in latex (png) or mathml?</del>
  - [x] Rename place to country in text on /place/ page

**Comment by rgrp** [comment]
All sound good though I'd -1 the "fork me on github" - i don't think you need this right now (more for a code site).

**Comment by GregoryRhysEvans** [comment]
I have changed the "beta" logo to a smaller font with a different colour. It is no longer part of the image and should now be configurable in the css.

**Comment by rgrp** [comment]
FIXED.
