### ISSUE TITLE
"This is a demo" text on the website

### ISSUE THREAD

**Issue by rgrp** [cybergreen-net/stats#10]
Put on about page and on front page.
 
**Demo**: This platform is a demo of version 2 of the CyberGreen metrics. As of now, the data and heat map simply illustrate the number (count) of infections and vulnerable devices. Our metrics are currently in development and undergoing review. Cybergreen metrics-based measurement and visualization will be finalized in December 2016.

**Feedback**: your feedback is valuable to us. If you have any questions, comments or suggestions about this demo, please [let us know](https://www.cybergreen.net/contact/)

**Comment by GregoryRhysEvans** [comment]
Text is now on "About" and home page.
