### ISSUE TITLE
country map not displayed correctly

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats#6]
The small map has some issues: 
  * the scroll bar is unnecessary (right scrollbar)
  * the combo box for the risks is mis-placed (probably causing the scroll bar to be present)

tested on Google Chrome 51.0.2704.79  os x  with 100% font size (the default).

![image](https://cloud.githubusercontent.com/assets/750019/15970295/e29e3d20-2f6e-11e6-8a02-b8d1a1a3b011.png)

**Comment by rgrp** [comment]
@aaronkaplan the scroll bar is happening because of the wrap of the drop-downs. This is already on the list to fix and we'll do it asap.

**Comment by aaronkaplan** [comment]
On Sat, Jun 11, 2016 at 05:13:56AM -0700, Rufus Pollock wrote:
> @aaronkaplan the scroll bar is happening because of the wrap of the drop-downs. This is already on the list to fix and we'll do it asap.
> 


cool, thanks! 

Beest,
a.
